language: python
python:
    - 2.7
    - 3.6
install:
    - pip install flake8
script:
    - flake8 . --count --max-complexity=10 --max-line-length=92 --statistics
notifications:
    on_success: change
    on_failure: change  # `always` will be the setting once code changes slow down
